export enum cartMutation {
  SET_GOODS_ITEM_MAP = "SET_GOODS_ITEM_MAP",
  SET_COUNT = "SET_COUNT",
  SET_GOODS_COUNT = "SET_GOODS_COUNT",
  DELETE_GOODS_POSITION = "DELETE_GOODS_POSITION",
}

export enum cartActions {
  ADD_GOODS = "ADD_GOODS",
  REMOVE_GOODS = "REMOVE_GOODS",
  REMOVE_GOODS_POSITION = "REMOVE_GOODS_POSITION",
}
